title: ShinHyeonJin - Portfolio
description: Programmer
site_title: 'ShinHyeonJin - Portfolio Page'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: P105XY
blog_url: https://www.notion.so/12d1e33e785a4cf69af52bb07bf45401?pvs=4
email: immahj0328@gmail.com
keybase_username: P105XY

# absolute or relative
profile_picture: assets/images/portrait.jpeg

# Google Analytics ID
google_analytics: 